// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJqrVgfHFKpCNYYqMW1izS0bLYgORxtu0',
    appId: '1:203049160516:web:2e9d443b75dd5ed8751111',
    messagingSenderId: '203049160516',
    projectId: 'final-5743d',
    authDomain: 'final-5743d.firebaseapp.com',
    storageBucket: 'final-5743d.appspot.com',
    measurementId: 'G-21VG7XMZZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7IWG3XQ2OFAeV7RtuKGjuS5JWTsVSRKY',
    appId: '1:203049160516:android:e65c28e5b48a33e0751111',
    messagingSenderId: '203049160516',
    projectId: 'final-5743d',
    storageBucket: 'final-5743d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2kOoFBXxaUpe94pfyjNVGfM_nEpXBdOE',
    appId: '1:203049160516:ios:a8aab604e78b4669751111',
    messagingSenderId: '203049160516',
    projectId: 'final-5743d',
    storageBucket: 'final-5743d.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2kOoFBXxaUpe94pfyjNVGfM_nEpXBdOE',
    appId: '1:203049160516:ios:60fbacace4fac424751111',
    messagingSenderId: '203049160516',
    projectId: 'final-5743d',
    storageBucket: 'final-5743d.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
